# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_initial_users'),
        ('board', '0002_initial_statuses'),
    ]

    operations = [
    ]
